# Generated by Django 5.1.1 on 2024-10-16 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_nombre_tipobasura_tipo_basura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='tipo_alerta',
        ),
    ]
