# Generated by Django 5.1.1 on 2024-10-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_alerta_estado_remove_alerta_tipo_alerta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='compartidos',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='likes',
        ),
    ]
