# Generated by Django 5.1.1 on 2024-10-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_comunicado_compartidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='likes',
        ),
    ]
