# Generated by Django 5.1.1 on 2024-10-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_evento_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicioMunicipal',
        ),
    ]
